#!/bin/bash

. common

rm -f broken-packages
basedir=${PWD}

# Add temporary repository to pacman.conf
rm pacman-*.conf
cp /usr/share/devtools/pacman-${repo}.conf .
sed "73i[kde-build]\nServer = file:///${basedir}/kde-build-repo\nSigLevel = Never\n" -i pacman-${repo}.conf

# Create temporary repository
rm -fr kde-build-repo
mkdir kde-build-repo
repo-add -n kde-build-repo/kde-build.db.tar > /dev/null 2>&1

# Pass i686 as argument if you want to build i686 packages on a x86_64 system
arch=$1
[[ -z ${arch} ]] && arch=$(uname -m)

# Cleanup package cache
arch-nspawn "/var/lib/archbuild/${repo}-${arch}/root" rm -f /var/cache/pacman/pkg/*

# Build packages
for i in ${depPkgName}; do
  _pushd build/${i}/${svnbranch}
    arch-nspawn \
      -C "${basedir}/pacman-${repo}.conf" \
      -M "/usr/share/devtools/makepkg-${arch}.conf" \
      "/var/lib/archbuild/${repo}-${arch}/root" \
      pacman -Syu --noconfirm
    setarch ${arch} sudo makechrootpkg -r /var/lib/archbuild/${repo}-${arch} -c -n || exit 1
    cp $(makepkg --packagelist) ${basedir}/kde-build-repo
    repo-add -n ${basedir}/kde-build-repo/kde-build.db.tar ${basedir}/kde-build-repo/*.pkg.tar.xz > /dev/null 2>&1
  _popd
done

for i in ${optPkgName}; do
  _pushd build/${i}/${svnbranch}
    arch-nspawn \
      -C "${basedir}/pacman-${repo}.conf" \
      -M "/usr/share/devtools/makepkg-${arch}.conf" \
      "/var/lib/archbuild/${repo}-${arch}/root" \
      pacman -Syu --noconfirm
    setarch ${arch} sudo makechrootpkg -r /var/lib/archbuild/${repo}-${arch} -c -n || ( echo ${i} >> ${basedir}/broken-packages )
  _popd
done

if [ -s broken-packages ]; then
  echo "Broken packages:"
  cat broken-packages
else
  echo "All packages built successfully!"
fi
