#!/bin/bash

. common

if [ "$#" -lt 2 ]; then
  echo "Usage: ${0} <package> <repo>"
  echo "Example: ${0} kio extra"
  exit 1
fi

basedir=${PWD}
package=$1
repo=$2
arch=$3

# Add temporary repository to pacman.conf
rm extra*.conf
cp /usr/share/devtools/pacman.conf.d/${repo}.conf .
sed "73i[build]\nServer = file:///${basedir}/build-repo\nSigLevel = Never\n" -i ${repo}.conf

# Pass i686 as argument if you want to build i686 packages on a x86_64 system
[[ -z ${arch} ]] && arch=$(uname -m)

# Cleanup package cache
arch-nspawn "${buildroot}/${repo}-${arch}/root" rm -f /var/cache/pacman/pkg/*

# Build package
_pushd build/${package}
  arch-nspawn \
    -C "${basedir}/${repo}.conf" \
    -M "/usr/share/devtools/makepkg.conf.d/${arch}.conf" \
    "${buildroot}/${repo}-${arch}/root" \
    pacman -Syu --noconfirm
  setarch ${arch} sudo makechrootpkg -r "${buildroot}/${repo}-${arch}" -c -n
_popd
