#!/bin/bash

. common

rm -f broken-packages
basedir=${PWD}

# Add temporary repository to pacman.conf
rm extra*.conf
cp /usr/share/devtools/pacman.conf.d/${repo}.conf .
sed "72i[build]\nServer = file:///${basedir}/build-repo\nSigLevel = Never\n" -i ${repo}.conf

# Create temporary repository
rm -fr build-repo
mkdir build-repo
repo-add -n build-repo/build.db.tar > /dev/null 2>&1

# Pass i686 as argument if you want to build i686 packages on a x86_64 system
arch=$1
[[ -z ${arch} ]] && arch=$(uname -m)

# Cleanup package cache
arch-nspawn "${buildroot}/${repo}-${arch}/root" rm -f /var/cache/pacman/pkg/*

# Build packages
for i in ${depPkgName}; do
  _pushd build/${i}
    arch-nspawn \
      -C "${basedir}/${repo}.conf" \
      -M "/usr/share/devtools/makepkg-${arch}.conf" \
      "${buildroot}/${repo}-${arch}/root" \
      pacman -Syuu --noconfirm
    setarch ${arch} sudo makechrootpkg -r "${buildroot}/${repo}-${arch}" -c -n || exit 1
    cp $(makepkg --packagelist) ${basedir}/build-repo
    repo-add -n ${basedir}/build-repo/build.db.tar ${basedir}/build-repo/*.pkg.tar.zst > /dev/null 2>&1
  _popd
done

for i in ${optPkgName}; do
  _pushd build/${i}
    arch-nspawn \
      -C "${basedir}/${repo}.conf" \
      -M "/usr/share/devtools/makepkg-${arch}.conf" \
      "${buildroot}/${repo}-${arch}/root" \
      pacman -Syuu --noconfirm
    setarch ${arch} sudo makechrootpkg -r "${buildroot}/${repo}-${arch}" -c -n || ( echo ${i} >> ${basedir}/broken-packages )
  _popd
done

if [ -s broken-packages ]; then
  echo "Broken packages:"
  cat broken-packages
else
  echo "All packages built successfully!"
fi
