#!/bin/bash

. common

for i in ${depPkgName} ${optPkgName} kde-l10n kde-meta; do
	if [ -d "build/${i}" ]; then
		_pushd build/${i}
		echo "${i}..."
		svn update
		_popd
	else
		_pushd build
		archco ${i}
		_popd
	fi
done
