#!/bin/bash

. common

if [ ! -d build ]; then
    svn checkout -N svn+ssh://svn-packages@nymeria.archlinux.org/srv/repos/svn-packages/svn build
fi

pushd build
svn update ${depPkgName} ${optPkgName} kde-l10n kde-meta
popd