#!/bin/bash

. common

if [ ! -d build ]; then
    svn checkout -N svn+ssh://svn-packages@repos.archlinux.org/srv/repos/svn-packages/svn build
fi

pushd build
    svn update ${depPkgName} ${optPkgName}
popd
