#!/bin/bash

. common

if [ "$1" = "" ]; then
    echo "Usage: ${0} <comment>"
    exit 1
fi

if [ -d build ]; then
  cd build

  unset pkgs
  for i in ${depPkgName} ${optPkgName}; do
    [ -d $i ] && pkgs="${pkgs} ${i}"
  done

  svn commit -m "${1}" ${pkgs}
fi
