#!/bin/bash

. common

rsync -e ssh -c -h -L --progress --partial ftparchlinux@depot.kde.org:${branch}/applications/${dirver}/src/*.xz{,.sig} ${SRCDEST}/

if ${l10n}; then
    rsync -e ssh -c -h -L --progress --partial ftparchlinux@depot.kde.org:${branch}/applications/${dirver}/src/kde-l10n/*.xz{,.sig} ${SRCDEST}/
fi
