#!/bin/bash

. common

rsync -e ssh -c -h -L --progress --partial ftparchlinux@ftpmaster.kde.org:${branch}/${dirver}/src/*.xz ${SRCDEST}/
rsync -e ssh -c -h -L --progress --partial ftparchlinux@ftpmaster.kde.org:${branch}/${dirver}/src/kde-l10n/*.xz ${SRCDEST}/
