#!/bin/bash

. common

pkglist=''

for i in oxygen-icons kde-wallpapers; do
	_pushd build/${i}/${svnbranch}
	. PKGBUILD
	pkgfile="build/${i}/${svnbranch}/${i}-${pkgver}-${pkgrel}-any${PKGEXT}"
	pkglist="${pkglist} ${pkgfile}"
	_popd
done

for i in ${depPkgName} ${optPkgName}; do
	_pushd build/${i}/${svnbranch}
	unset pkgname
	. PKGBUILD
	for j in ${pkgname[@]}; do
		pkgfile="build/${i}/${svnbranch}/${j}-${pkgver}-${pkgrel}-${CARCH}${PKGEXT}"
		pkglist="${pkglist} ${pkgfile}"
	done
	_popd
done

sudo pacman -U ${pkglist}