#!/bin/bash

. common

pkglist=''

for i in ${depPkgName} ${optPkgName}; do
    _pushd build/${i}/${svnbranch}
        pkglist="${pkglist} $(makepkg --packagelist)"
    _popd
done

sudo pacman -U ${pkglist}
