#!/bin/bash

if [ ! -d build ]; then
  exit 1
fi

. common

for pkg in ${depPkgName} ${optPkgName}; do
	_pushd build/${pkg}/${svnbranch}
	unset pkgname
	unset pkgver
	unset pkgrel
	unset arch
	. PKGBUILD
	for _arch in ${arch[@]}; do
		for _pkgname in ${pkgname[@]}; do
			pkgfile=${_pkgname}-${pkgver}-${pkgrel}-${_arch}${PKGEXT}
			if [ -f "${pkgfile}" ]; then
				echo "checking ${pkgfile}..."
				namcap ${pkgfile} > ${pkgfile}-namcap.log
			fi
		done
	done
	_popd
done
