#!/bin/bash

if [ ! -d build ]; then
  exit 1
fi

. common
rm -f namcap.log
basedir=${PWD}

for pkg in ${depPkgName} ${optPkgName}; do
    _pushd build/${pkg}
    for _pkgfile in $(makepkg --packagelist); do
        namcap ${_pkgfile}
    done
    _popd
done

cat namcap.log
