#!/bin/sh

if [ ! -d build ]; then
  exit 1
fi

cat $(find build/*/${svnbranch} -name *-namcap.log) | grep -v -e '/etc/ssl/certs/ca-certificates.crt' \
			-e 'on your system is a testing release' \
			-e 'hicolor-icon-theme' \
			-e 'gcc-libs' \
			-e 'shared-mime-info' \
			-e 'points to non-existing /usr/share/doc/' \
			-e 'Potential non-FHS man page (usr/share/doc' \
			-e 'Potential non-FHS info page (usr/share/doc' \
			-e "Dependency included and not needed ('kdebase-runtime')" \
			-e "Dependency included and not needed ('kdepim-runtime')" | less
