#!/bin/bash

server="pkgbuild.com"

. common

checkIntegrity() {
	if [ "$(sha1sum "${1}" | cut -d' ' -f1)" != "$(ssh ${server} sha1sum "${2}" | cut -d' ' -f1)" ]; then
		return 1
	else
		return 0
	fi
}

echo "Downloading packages from $server..."
for i in ${depPkgName} ${optPkgName}; do
	_pushd build/${i}/${svnbranch}
	unset pkgname pkgrel arch
	. PKGBUILD
	for a in ${arch[@]}; do
		for j in ${pkgname[@]}; do
			if [ ! -f ${j}-${kdever}-${pkgrel}-${a}${PKGEXT} ]; then
				scp ${server}:"~/packages/${i}/${svnbranch}/${j}-${kdever}-${pkgrel}-${a}${PKGEXT}" .
			fi

			if [ -f ${j}-${kdever}-${pkgrel}-${a}${PKGEXT} ]; then
				echo "Checking ${j} ${a} integrity..."
				if ! checkIntegrity ${j}-${kdever}-${pkgrel}-${a}${PKGEXT} "~/packages/${i}/${svnbranch}/${j}-${kdever}-${pkgrel}-${a}${PKGEXT}"; then
					echo "ERROR: ${j} ${a} corrupted"
					rm ${j}-${kdever}-${pkgrel}-${a}${PKGEXT} ${j}-${kdever}-${pkgrel}-${a}${PKGEXT}.sig &> /dev/null
					exit 1
				fi

				if [ ! -f ${j}-${kdever}-${pkgrel}-${a}${PKGEXT}.sig ]; then
					echo "Signing and uploading signatures..."
					gpg --detach-sign --use-agent ${j}-${kdever}-${pkgrel}-${a}${PKGEXT}
					scp ${j}-${kdever}-${pkgrel}-${a}${PKGEXT}.sig ${server}:"~/packages/${i}/${svnbranch}/"
				fi
			else
				echo "WARNING: ${j} ${a} not found"
			fi
		done
	done
	_popd
done
