#!/bin/bash

. common

if [ "$#" -lt 2 ]; then
	echo "Usage: ${0} <source> <target>"
	echo "Example: ${0} trunk kde-unstable"
	exit 1
fi

source=$1
target=$2

for pkg in ${depPkgName} ${optPkgName}; do
    if [ -d build/${pkg} ]; then
        _pushd build/${pkg}
        [ -d ${target} ] && svn rm --force ${target}
        svn cp ${source} ${target}
        _popd
    fi
done
