#!/bin/bash

. common

for i in ${depPkgName} ${optPkgName}; do

    _pushd build/${i}/${svnbranch}
    sed -r "s|https://download.kde.org/.*stable/|https://download.kde.org/${branch}/|g" -i PKGBUILD
    sed -r "s|pkgver=.*|pkgver=${version}|g" -i PKGBUILD
    sed -r 's|pkgrel=.*|pkgrel=1|g' -i PKGBUILD
    updpkgsums
    _popd
done
