#!/bin/bash

. common

broken=''

for i in `cat kde-dep-packages`; do
	pushd build/${i}/${svnbranch}
	makepkg -isLc --noconfirm || exit 1
	popd
done

for i in `cat kde-opt-packages`; do
	pushd build/${i}/${svnbranch}
	makepkg -sLc --noconfirm || broken="${broken} ${i}"
	popd
done

if $l10n; then
	for i in $(getL10nPkgNames); do
		pushd build/${i}/${svnbranch}
		makepkg -sLc --noconfirm || broken="${broken} ${i}"
		popd
	done
fi

if [ "${broken}" != "" ]; then
	echo "Broken packages: ${broken}"
fi
