#!/bin/bash

. common

broken=''

for i in ${depPkgName}; do
	_pushd build/${i}/${svnbranch}
	if ${usechroot}; then
		sudo makechrootpkg -u -d -r ${chroot} -- --noconfirm || exit 1
	else
		makepkg -isL --noconfirm || exit 1
	fi
	_popd
done

for i in ${optPkgName}; do
	_pushd build/${i}/${svnbranch}
	makepkg -$(${installall} && echo 'i')sL --noconfirm || broken="${broken} ${i}"
	_popd
done

if [ "${broken}" != "" ]; then
	echo "Broken packages: ${broken}"
fi
