#!/bin/bash

. common

broken=''

for i in ${depPkgName}; do
	_pushd build/${i}/${svnbranch}
	makepkg -isL --noconfirm || exit 1
	_popd
done

for i in ${optPkgName} ${l10nPkgName}; do
	_pushd build/${i}/${svnbranch}
	makepkg -$(${installall} && echo 'i')sL --noconfirm || broken="${broken} ${i}"
	_popd
done


if [ "${broken}" != "" ]; then
	echo "Broken packages: ${broken}"
fi
