#!/bin/bash

cd build

for i in `cat ../kde-dep-packages ../kde-opt-packages`; do
	cd ${i}/trunk
	namcap ${i}-*.pkg.tar.gz | tee namcap.log
	cd ../..
done

for i in `cat ../kde-l10n-names`; do
	pkglang=$(echo "${i}" | tr [:upper:] [:lower:])
	cd kde-l10n-${pkglang}/trunk
	namcap kde-l10n-${pkglang}-*.pkg.tar.gz | tee namcap.log
	cd ../..
done

cd ..