#!/bin/bash

. common

copkg() {
	svn co svn+ssh://svn.archlinux.org/srv/svn-packages/${1} ${2}
}


for i in `cat kde-dep-packages kde-opt-packages`; do
	copkg ${i} build/${i}
done

if $l10n; then
	for i in $(getL10nPkgNames); do
		copkg ${i} build/${i}
	done
fi
