#!/bin/bash

. common

_pushd build

for i in ${depPkgName} ${optPkgName}; do
	_pushd ${i}/${svnbranch}
	rm -rf pkg src *.log* *${PKGEXT}
	_popd
done

if [ -d kde-l10n ]; then
	_pushd kde-l10n/${svnbranch}
	rm -rf pkg src *.log* *${PKGEXT}
	_popd
fi

_popd
