#!/bin/bash

. common

for i in ${depPkgName} ${optPkgName}; do
	_pushd build/${i}/${svnbranch}
	rm -rf pkg src *.log* *${PKGEXT} *.part *~
	_popd
done

if ${l10n}; then
	_pushd build/${i}/${svnbranch}
	rm -rf pkg src *.log* *${PKGEXT} *.part *~
	_popd
fi