#!/bin/bash

. common

pushd build

for i in `cat ../kde-dep-packages ../kde-opt-packages`; do
	pushd ${i}/${svnbranch}
	rm -rf pkg src
	popd
done

if $l10n; then
	for i in $(getL10nPkgNames); do
		pushd ${i}/${svnbranch}
		rm -rf pkg src
		popd
	done
fi

popd
