#!/bin/bash

. common

if [ "$1" = "" ]; then
	echo "Usage: ${0} <comment>"
	exit 1
fi

for i in ${depPkgName} ${optPkgName} kde-meta; do
	_pushd build/${i}/${svnbranch}
	echo "${i}..."
	svn commit -m"${1}" || exit 1
	_popd
done

if ${l10n}; then
	_pushd build/kde-l10n/${svnbranch}
	echo "kde-10n..."
	svn commit -m"${1}" || exit 1
	_popd
fi
