#!/bin/bash

. common

if [ "$1" = "" ]; then
	echo "Usage: ${0} <comment>"
	exit 1
fi


for i in `cat kde-dep-packages kde-opt-packages` ${l10nPkgName}; do
	pushd build/${i}/${svnbranch}
	svn commit -m"${1}" || exit 1
	popd
done
