#!/bin/bash

. common

pkgver=4.5

pkgs=('kdeaccessibility'
         'kdeadmin'
         'kdeartwork'
         'kdebase'
         'kdeedu'
         'kdegames'
         'kdegraphics'
         'kdemultimedia'
         'kdenetwork'
         'kdepim'
         'kdeplasma-addons'
         'kdesdk'
         'kdetoys'
         'kdeutils'
         'kdewebdev')

pkgs=($(echo ${pkgs[@]} | sort -u))

echo     '# $Id: $'
echo -e  '# Maintainer: Andrea Scarpino <andrea@archlinux.org>'
echo -e  '# Contributor: Pierre Schmitz <pierre@archlinux.de>\n'
echo     'pkgbase=kde-meta'
echo -en 'pkgname=('
ct=0
for k in ${pkgs[@]}; do
	[ $ct -gt 0 ] && echo -en "\n         "
	echo -n "'kde-meta-${k}'"
	ct=$(($ct+1))
done
echo    ')'
echo     "pkgver=${pkgver}"
echo     "pkgrel=1"
echo     "arch=('any')"
echo     "url='http://www.archlinux.org/'"
echo     "license=('GPL')"
echo -e  "groups=('kde-meta')\n"

for i in ${pkgs[@]}; do
	_pushd build/${i}/${svnbranch}
	echo     "package_kde-meta-${i}() {"
	echo -e  "\tpkgdesc=('Meta package for ${i}')"
	echo -en '\tdepends=('
	ct=0
	unset pkgname
	. PKGBUILD
	for j in ${pkgname[@]}; do
		[ $ct -gt 0 ] && echo -en "\n\t         "
		echo -n "'${j}'"
		ct=$(($ct+1))
	done
	echo     ')'
	echo -e  "\treplaces=('${i}')"
	echo -e  "\tconflicts=('${i}')"
	echo -e  "}\n"
	_popd
done
