#!/bin/bash

. common

checkIntegrity() {
	if [ "$(md5sum "${1}" | cut -d' ' -f1)" != "$(ssh ktown.kde.org md5sum "${2}" | cut -d' ' -f1)" ]; then
		return 1
	else
		return 0
	fi
}

for i in `cat kde-dep-packages kde-opt-packages`; do
	if [ ! -f "${SRCDEST}/${i}-${kdever}.tar.bz2" ]; then
		scp ktown.kde.org:~/${branch}/${dirver}/src/${i}-${kdever}.tar.bz2 ${SRCDEST}/
	fi

	if checkIntegrity "${SRCDEST}/${i}-${kdever}.tar.bz2" "~/${branch}/${dirver}/src/${i}-${kdever}.tar.bz2"; then
		echo "${i}-${kdever}.tar.bz2 ok"
	else
		echo "${i}-${kdever}.tar.bz2 corrupted"
		exit 1
	fi
done

if $l10n; then
	for i in `cat kde-l10n-names`; do
		if [ ! -f "${SRCDEST}/kde-l10n-${i}-${kdever}.tar.bz2" ]; then
			scp ktown.kde.org:~/${branch}/${dirver}/src/kde-l10n/kde-l10n-${i}-${kdever}.tar.bz2 ${SRCDEST}/
		fi

		if checkIntegrity "${SRCDEST}/kde-l10n-${i}-${kdever}.tar.bz2" "~/${branch}/${dirver}/src/kde-l10n/kde-l10n-${i}-${kdever}.tar.bz2"; then
			echo "kde-l10n-${i}-${kdever}.tar.bz2 ok"
		else
			echo "kde-l10n-${i}-${kdever}.tar.bz2 corrupted"
			exit 1
		fi
	done
fi
