#!/bin/bash

. common

checkIntegrity() {
	if [ "$(sha1sum "${1}" | cut -d' ' -f1)" != "$(ssh ftpmaster.kde.org sha1sum "${2}" | cut -d' ' -f1)" ]; then
		return 1
	else
		return 0
	fi
}

for i in `ssh ftpmaster.kde.org ls ${branch}/${dirver}/src/*-${kdever}.tar.bz2`; do

	if [ ! -f "${SRCDEST}/$(basename ${i})" ]; then
		scp ftpmaster.kde.org:~/${i} ${SRCDEST}/
	fi

	if checkIntegrity "${SRCDEST}/$(basename ${i})" "~/${i}"; then
		echo "$(basename ${i}) ok"
	else
		echo "$(basename ${i}) corrupted"
		exit 1
	fi
done

if ${l10n}; then
	for i in `ssh ftpmaster.kde.org ls ${branch}/${dirver}/src/kde-l10n/*-${kdever}.tar.bz2`; do

		if [ ! -f "${SRCDEST}/$(basename ${i})" ]; then
			scp ftpmaster.kde.org:~/${i} ${SRCDEST}/
		fi

		if checkIntegrity "${SRCDEST}/$(basename ${i})" "~/${i}"; then
			echo "$(basename ${i}) ok"
		else
			echo "$(basename ${i}) corrupted"
			exit 1
		fi
	done
fi
