#!/bin/bash

. common

pkglist=''

for i in ${depPkgName} ${optPkgName}; do
	_pushd build/${i}/${svnbranch}
	unset pkgname
	. PKGBUILD
	for j in ${pkgname[@]}; do
		pkglist="${pkglist} ${j}"
	done
	_popd
done

echo ${pkglist}
