#!/bin/bash

pkglist=''

for i in `cat kde-dep-packages kde-opt-packages`; do
	for j in build/${i}/trunk/${i}-*.pkg.tar.gz; do
		if [[ -f ${j} ]]; then
			pkgfile=${j}
		fi
	done
	pkglist="${pkglist} ${pkgfile}"
done

for i in `cat kde-l10n-names`; do
	pkglang=$(echo "${i}" | tr [:upper:] [:lower:])
#	pkglist="${pkglist} build/kde-l10n-${pkglang}/trunk/kde-l10n-${pkglang}-*.pkg.tar.gz"
done

sudo pacman -U ${pkglist}
