#!/bin/bash

. common

pkglist=''

for i in ${depPkgName} ${optPkgName}; do
	_pushd build/${i}/${svnbranch}
	unset pkgname
	. PKGBUILD
	for j in ${pkgname[@]}; do
		pkgfile=${j}-${pkgver}-${pkgrel}-${CARCH}${PKGEXT}
		pkglist="${pkglist} ${pkgfile}"
	done
	_popd
done


sudo pacman -U ${pkglist}
