#!/bin/bash

. common

pkglist=''

for i in `cat kde-dep-packages kde-opt-packages`; do
	for j in build/${i}/${svnbranch}/${i}-*.pkg.tar.gz; do
		if [[ -f ${j} ]]; then
			pkgfile=${j}
		fi
	done
	pkglist="${pkglist} ${pkgfile}"
done


#if $l10n; then
#	for i in $(getL10nPkgNames); do
#		pkglist="${pkglist} build/${i}/${svnbranch}/${i}-*.pkg.tar.gz"
#	done
#fi

sudo pacman -U ${pkglist}
