#!/bin/bash

. common

if [ "$#" -lt 2 ]; then
	echo "Usage: ${0} <repo-from> <repo-to>"
	echo "Example: ${0} staging extra"
	exit 1
fi

repofrom=$1
repoto=$2

ssh gerolde.archlinux.org /arch/db-move $repofrom $repoto ${depPkgName} ${optPkgName}

if ${l10n}; then
	ssh gerolde.archlinux.org /arch/db-move $repofrom $repoto kde-l10n
fi
