#!/bin/bash

. common

for i in ${depPkgName} ${optPkgName} ${l10nPkgName}; do
	_pushd build/${i}/$svnbranch
	for a in ${arch[@]}; do
		if [ -f ${i}-${pkgver}-${pkgrel}-${a}${PKGEXT} ]; then
			archrelease ${repo}-${a}
		fi
	done
	_popd
done

#ssh gerolde.archlinux.org /arch/db-update $repo
#ssh gerolde.archlinux.org /arch/misc-scripts/ftpdir-cleanup $repo $CARCH
#ssh gerolde.archlinux.org /arch/misc-scripts/ftpdir-cleanup $repo any
