#!/bin/bash

. common

for i in `cat kde-dep-packages kde-opt-packages` ${l10nPkgName}; do
	_pushd build/${i}/$svnbranch
	$pwd/../common/urelease $repo-$CARCH
	_popd
done

# FIXME: this wont work with splitted packages
#ssh archlinux.org /arch/db-update $repo $CARCH
#ssh archlinux.org /arch/misc-scripts/ftpdir-cleanup $repo $CARCH
