#!/bin/bash

. common

arch=$1
[[ -z ${arch} ]] && arch=${CARCH}

for i in ${depPkgName} ${optPkgName}; do
	_pushd build/${i}/$svnbranch
	archrelease ${repo}-${arch}
	_popd
done

if [ "${any}" == "true" ]; then
	_pushd build/oxygen-icons/$svnbranch
	archrelease ${repo}-any
	_popd
fi

if [ "${l10n}" == "true" ]; then
	_pushd build/kde-l10n/$svnbranch
	archrelease ${repo}-any
	_popd
fi