#!/bin/bash

. common

broken=''

for i in `cat kde-dep-packages`; do
	pushd build/${i}/${svnbranch}
	mkdir pkg
	tar -xzf ${i}-*.pkg.tar.gz -C pkg
	makepkg -Rifc --noconfirm || exit 1
	popd
done

for i in `cat kde-opt-packages` ${l10nPkgName}; do
	pushd build/${i}/${svnbranch}
	mkdir pkg
	tar -xzf ${i}-*.pkg.tar.gz -C pkg
	makepkg -Rfc --noconfirm || broken="${broken} ${i}"
	popd
done


if [ "${broken}" != "" ]; then
	echo "Broken packages: ${broken}"
fi
