#!/bin/bash

. common

broken=''

for i in ${depPkgName}; do
	_pushd build/${i}/${svnbranch}
	#mkdir pkg
	#tar -xzf ${i}-*.pkg.tar.gz -C pkg
	makepkg -Rif --noconfirm || exit 1
	_popd
done

for i in ${optPkgName}; do
	_pushd build/${i}/${svnbranch}
	#mkdir pkg
	#tar -xzf ${i}-*.pkg.tar.gz -C pkg
	makepkg -R$(${installall} && echo 'i')f --noconfirm || broken="${broken} ${i}"
	_popd
done


if [ "${broken}" != "" ]; then
	echo "Broken packages: ${broken}"
fi
