#!/bin/bash

. common


for i in `cat kde-dep-packages kde-opt-packages` ${l10nPkgName}; do
	_pushd build/${i}/${svnbranch}
	namcap PKGBUILD > namcap-PKGBUILD.log
	unset pkgname
	. PKGBUILD
	for j in ${pkgname[@]}; do
		pkgfile=${j}-${pkgver}-${pkgrel}-${CARCH}${PKGEXT}
		echo "checking ${pkgfile}..."
		namcap ${pkgfile} > namcap-${pkgfile}.log
	done
	_popd
done
