#!/bin/bash

. common

for i in ${depPkgName} ${optPkgName} ${l10nPkgName}; do
	_pushd build/${i}/${svnbranch}
	namcap PKGBUILD > namcap-PKGBUILD.log
	unset pkgname
	. PKGBUILD
	for j in ${pkgname[@]}; do
		if [ -f ${j}-${pkgver}-${pkgrel}-${CARCH}${PKGEXT} ]; then
			pkgfile=${j}-${pkgver}-${pkgrel}-${CARCH}${PKGEXT}
		else
			pkgfile=${j}-${pkgver}-${pkgrel}-any${PKGEXT}
		fi
		echo "checking ${pkgfile}..."
		namcap ${pkgfile} > namcap-${pkgfile}.log
	done
	_popd
done
