#!/bin/bash

. common

declare -a uploads

for pkg in ${depPkgName} ${optPkgName}; do
	_pushd build/${pkg}/${svnbranch}
	unset pkgname
	unset pkgver
	unset pkgrel
	unset arch
	. PKGBUILD
	for _arch in ${arch[@]}; do
		for _pkgname in ${pkgname[@]}; do
			pkgfile=${_pkgname}-${pkgver}-${pkgrel}-${_arch}${PKGEXT}
			echo "checking ${pkgfile}..."
			namcap ${pkgfile} > ${pkgfile}-namcap.log
		done
	done
	_popd
done