#!/bin/bash

. common

pkglist=''

# no need to display both arches
arch=x86_64

for i in ${depPkgName} ${optPkgName}; do
	_pushd build/${i}/${svnbranch}
	unset pkgname
	unset pkgver
	unset pkgrel
	. PKGBUILD
	for _pkgname in ${pkgname[@]}; do
		logfile="${_pkgname}-${pkgver}-${pkgrel}-${arch}${PKGEXT}-namcap.log"
		if [ -f "${logfile}" ]; then
			pkglist="${pkglist} ${logfile}"
		fi
	done
	_popd
done

cat ${pkglist} | grep -v -e '/etc/ssl/certs/ca-certificates.crt' \
		         -e 'on your system is a testing release' \
		         -e 'points to non-existing /usr/share/doc/' \
		         -e 'kdebase-runtime E: Dependency detected and not included (xine-lib)' \
		         -e 'Potential non-FHS man page (usr/share/doc' \
		         -e 'Potential non-FHS info page (usr/share/doc' \
		         -e "Dependency included and not needed ('kdebase-runtime')" \
		         -e "Dependency included and not needed ('kdepim-runtime')" \
	| less
