#!/bin/bash

. common

pkglist=''

for i in ${depPkgName} ${optPkgName} ${l10nPkgName}; do
	_pushd build/${i}/${svnbranch}
	unset pkgname
	. PKGBUILD
	for j in ${pkgname[@]}; do
		if [ -f ${j}-${pkgver}-${pkgrel}-${CARCH}${PKGEXT} ]; then
			pkgfile=${j}-${pkgver}-${pkgrel}-${CARCH}${PKGEXT}
		else
			pkgfile=${j}-${pkgver}-${pkgrel}-any${PKGEXT}
		fi
		pkglist="${pkglist} build/${i}/${svnbranch}/namcap-PKGBUILD.log build/${i}/${svnbranch}/namcap-${pkgfile}.log"
	done
	_popd
done

cat ${pkglist} | less
