#!/bin/bash

if [ ! -f PKGBUILD ]; then
	echo "PKGBUILD not found!"
	exit 1
fi

# makepkg -o

. PKGBUILD

cd src/$pkgbase-$pkgver

if [ "$pkgname" == 'kdebase' ]; then
	cd apps
fi

getSubdirs() {
	grep -v '^#' "$1" \
	| grep -o 'add_subdirectory([^)]*' \
	| sed -e 's/add_subdirectory(//' \
	| grep -v -e 'doc' -e 'cmake' \
	| sort -u
}


if [ "$pkgbase" == 'kdeplasma-addons' ]; then
	for i in $(getSubdirs CMakeLists.txt); do
		for j in $(getSubdirs $i/CMakeLists.txt); do
			subdirs=(${subdirs[@]} "$(basename $i)-$j")
		done
	done
else
	subdirs=($(getSubdirs CMakeLists.txt))
fi


echo "pkgbase=${pkgbase}"
echo -n 'pkgname=('
ct=0
for i in ${subdirs[@]}; do
	[ $ct -gt 0 ] && echo -en "\n         "
	echo -n "'${pkgbase}-$(echo "${i}" | tr [:upper:] [:lower:])'"
	ct=$(($ct+1))
done
echo ')'
echo


for i in ${subdirs[@]}; do
	echo "package_${pkgbase}-$(echo "${i}" | tr [:upper:] [:lower:])() {"
	echo -e "\tpkgdesc=''"
	echo -e "\tdepends=($(for d in ${depends[@]};do echo -n "'${d}' ";done))"
	echo -e "\tinstall='${install}'"
	echo -e "\tcd \$srcdir/build/${i}"
	echo -e "\tmake DESTDIR=\$pkgdir install"
	if [ -d "doc/${i}" ]; then
		echo -e "\tcd \$srcdir/build/doc/${i}"
		echo -e "\tmake DESTDIR=\$pkgdir install"
	fi
	echo "}"
	echo
done