#!/bin/bash

if [ "$1" = "" ]; then
	echo "Usage: ${0} <comment>"
	exit 1
fi

cd build

for i in `cat ../kde-dep-packages ../kde-opt-packages`; do
	cd ${i}/trunk
	svn commit -m"${1}" || exit 1
	cd ../..
done

for i in `cat ../kde-l10n-names`; do
	pkglang=$(echo "${i}" | tr [:upper:] [:lower:])
	cd kde-l10n-${pkglang}/trunk
	svn commit -m"${1}" || exit 1
	cd ../..
done

cd ..
