#!/bin/bash

. common


if [ "$#" -eq 2 ]; then
	echo "Usage: ${0} <source> <target>"
	echo "Example: ${0} trunk kde-unstable"
	exit 1
fi

source=$1
target=$2

for i in ${depPkgName} ${optPkgName} kde-l10n; do
	svn rm --force build/${i}/${target}
	svn cp build/${i}/${source} build/${i}/${target}
done
