#!/bin/bash

. common

pkglist=''

for i in ${depPkgName} ${optPkgName} ${l10nPkgName}; do
	_pushd build/${i}/${svnbranch}
	unset pkgname
	. PKGBUILD
	for j in ${pkgname[@]}; do
		pkglist="${pkglist} $(pacman -Qq ${j} 2> /dev/null)"
	done
	_popd
done

sudo pacman -Rcn ${pkglist}
