#!/bin/bash

. common

for i in ${depPkgName} ${optPkgName}; do

	_pushd build/${i}/${svnbranch}
	sed -r "s|http://download.kde.org/.*stable/|http://download.kde.org/${branch}/|g" -i PKGBUILD

	# configure debug build; see http://techbase.kde.org/Development/CMake/Build_Types
	# @TODO: add debug to existing options array (there are none atm anyway)
	sed -ie "/options=('debug')/d" -i PKGBUILD
	if $debug; then
		sed -r 's|-DCMAKE_BUILD_TYPE=Release|-DCMAKE_BUILD_TYPE=RelWithDebInfo|g' -i PKGBUILD
		if grep -q 'options=(' PKGBUILD; then
			echo 'Warning: options array already exists!'
		else
			echo "options=('debug')" >> PKGBUILD
		fi
	else
		sed -r 's|-DCMAKE_BUILD_TYPE=RelWithDebInfo|-DCMAKE_BUILD_TYPE=Release|g' -i PKGBUILD
	fi

    sed -r "s|pkgver=.*|pkgver=${kdever}|g" -i PKGBUILD
    sed -r 's|pkgrel=.*|pkgrel=1|g' -i PKGBUILD
    updpkgsums
    _popd
done

if ${l10n}; then
	echo "creating kde-l10n PKGBUILD..."
	./create-l10n > build/kde-l10n/${svnbranch}/PKGBUILD
fi
