#!/bin/bash

. common

for i in ${depPkgName} ${optPkgName}; do

	_pushd build/${i}/${svnbranch}
	sed -r "s|http://download.kde.org/.*stable/|http://download.kde.org/${branch}/|g" -i PKGBUILD

	$pwd/../common/updpkg ${kdever}
	_popd
done

if ${l10n}; then
	echo "creating kde-l10n PKGBUILD..."
	./create-l10n > build/kde-l10n/${svnbranch}/PKGBUILD
fi
