#!/bin/bash

. common


for i in ${depPkgName} ${optPkgName}; do
	if [ ! -f ${SRCDEST}/${i}-${kdever}.tar.bz2 ]; then
		echo "${i}-${kdever}.tar.bz2 not found!"
		exit 1
	fi

	_pushd build/${i}/${svnbranch}
	sed -r "s|http://download.kde.org/.*stable/|http://download.kde.org/${branch}/|g" -i PKGBUILD

	# configure debug build; see http://techbase.kde.org/Development/CMake/Build_Types
	# @TODO: add !strip to existing optinos array (there are none atm anyway)
	sed -ie "/options=('!strip')/d" -i PKGBUILD
	if $debug; then
		sed -r 's|-DCMAKE_BUILD_TYPE=Release|-DCMAKE_BUILD_TYPE=RelWithDebInfo|g' -i PKGBUILD
		if grep -q 'options=(' PKGBUILD; then
			echo 'Warning: options array already exists!'
		else
			echo "options=('!strip')" >> PKGBUILD
		fi
	else
		sed -r 's|-DCMAKE_BUILD_TYPE=RelWithDebInfo|-DCMAKE_BUILD_TYPE=Release|g' -i PKGBUILD
	fi

	$pwd/../common/updpkg ${kdever}
	_popd
done

if $l10n; then
	for i in `cat kde-l10n-names`; do
		if [ ! -f ${SRCDEST}/kde-l10n-${i}-${kdever}.tar.bz2 ]; then
			echo "kde-l10n-${i}-${kdever}.tar.bz2 not found!"
			exit 1
		fi

		pkglang=$(echo "${i}" | tr [:upper:] [:lower:])
		_pushd build/kde-l10n-${pkglang}/${svnbranch}
		sed -r "s|http://download.kde.org/.*stable/|http://download.kde.org/${branch}/|g" -i PKGBUILD
		$pwd/../common/updpkg ${kdever}
		_popd
	done
fi
