#!/bin/bash

. common

declare -a uploads

for pkg in ${depPkgName} ${optPkgName}; do
	_pushd build/${pkg}/${svnbranch}
	unset pkgname
	unset pkgver
	unset pkgrel
	unset arch
	. PKGBUILD
	for _arch in ${arch[@]}; do
		for _pkgname in ${pkgname[@]}; do
			pkgfile=${_pkgname}-${pkgver}-${pkgrel}-${_arch}${PKGEXT}
			if [ -f "${pkgfile}" ]; then
				echo "found ${pkgfile}..."
				uploads+=("build/${pkg}/${svnbranch}/$pkgfile")

				sigfile="${pkgfile}.sig"
				if [ -f "${sigfile}" ]; then
					uploads+=("build/${pkg}/${svnbranch}/$sigfile")
				fi
			fi
		done
	done
	_popd
done

if {l10n}; then
	_pushd build/kde-l10n/${svnbranch}
	unset pkgname
	unset pkgver
	unset pkgrel
	unset arch
	. PKGBUILD
	for _pkgname in ${pkgname[@]}; do
		pkgfile=${_pkgname}-${pkgver}-${pkgrel}-${_arch}${PKGEXT}
		if [ -f "${pkgfile}" ]; then
			echo "found ${pkgfile}..."
			uploads+=("build/${pkg}/${svnbranch}/$pkgfile")

			sigfile="${pkgfile}.sig"
			if [ -f "${sigfile}" ]; then
				uploads+=("build/${pkg}/${svnbranch}/$sigfile")
			fi
		fi
	done
	_popd
fi

rsyncopts=(-e ssh -p --chmod=ug=rw,o=r -c -h -L --progress --partial -y)
if [[ ${#uploads[*]} -gt 0 ]]; then
	echo 'Uploading all package and signature files'
	rsync "${rsyncopts[@]}" "${uploads[@]}" "gerolde.archlinux.org:staging/$repo/" || die
fi
