#!/bin/bash

. common

for i in ${depPkgName} ${optPkgName}; do
	_pushd build/${i}/${svnbranch}
	unset pkgname
	. PKGBUILD
	for j in ${pkgname[@]}; do
		for a in ${arch[@]}; do
			if [ -f ${j}-${pkgver}-${pkgrel}-${a}${PKGEXT} ]; then
				pkgfile=${j}-${pkgver}-${pkgrel}-${a}${PKGEXT}
				rsync -p --chmod 'ug=rw,o=r' -c -h -L --progress "${pkgfile}" -e ssh gerolde.archlinux.org:staging/${repo}/
				if [ "$(md5sum "${pkgfile}" | cut -d' ' -f1)" != "$(ssh gerolde.archlinux.org md5sum "staging/${repo}/${pkgfile}" | cut -d' ' -f1)" ]; then
					echo "${pkgfile} got corrupted during upload!"
				fi
			fi
		done
	done
	_popd
done

if ${l10n}; then
	_pushd build/kde-l10n/${svnbranch}
	unset pkgname
	. PKGBUILD
	for i in ${pkgname[@]}; do
		pkgfile=${i}-${pkgver}-${pkgrel}-any${PKGEXT}
		rsync -p --chmod 'ug=rw,o=r' -c -h -L --progress "${pkgfile}" -e ssh gerolde.archlinux.org:staging/${repo}/
		if [ "$(md5sum "${pkgfile}" | cut -d' ' -f1)" != "$(ssh gerolde.archlinux.org md5sum "staging/${repo}/${pkgfile}" | cut -d' ' -f1)" ]; then
			echo "${pkgfile} got corrupted during upload!"
		fi
	done
fi