#!/bin/bash

. common

for i in ${depPkgName} ${optPkgName} ${l10nPkgName}; do
	_pushd build/${i}/${svnbranch}
	unset pkgname
	. PKGBUILD
	for i in ${pkgname[@]}; do
		if [ -f ${i}-${pkgver}-${pkgrel}-${CARCH}${PKGEXT} ]; then
			pkgfile=${i}-${pkgver}-${pkgrel}-${CARCH}${PKGEXT}
		else
			pkgfile=${i}-${pkgver}-${pkgrel}-any${PKGEXT}
		fi
		scp "${pkgfile}" gerolde.archlinux.org:staging/${repo}/
		if [ "$(md5sum "${pkgfile}" | cut -d' ' -f1)" != "$(ssh gerolde.archlinux.org md5sum "staging/${repo}/${pkgfile}" | cut -d' ' -f1)" ]; then
			echo "${pkgfile} got corrupted during upload!"
		fi
	done
	_popd
done
