#!/bin/bash

if [ "$#" -eq 0 ]; then
	echo "Usage: ${0} <pkgver>"
	exit 1
fi

if [ ! -f PKGBUILD ]; then
	echo "PKGBUILD not found!"
	exit 1
fi

# Be sure we've the sources
makepkg -g &>/dev/null || exit 1

sed -r "s|pkgver=.*|pkgver=${1}|g" -i PKGBUILD
sed -r 's|pkgrel=.*|pkgrel=1|g' -i PKGBUILD
{ rm PKGBUILD; awk '$0 ~ /^sha1sums/ {i = 1; system("makepkg -g 2>/dev/null")}; !i {print}; $0 ~ /\)/ {i = 0}' > PKGBUILD; } < PKGBUILD