#!/bin/bash

if [ "$#" -lt 2 ]; then
  echo "Usage: ${0} <package>"
  echo "Example: ${0} kio"
  exit 1
fi

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

. ${SCRIPTPATH}/common

basedir=${PWD}
package=$1

# Add temporary repository to pacman.conf
cp /usr/share/devtools/pacman.conf.d/${repo}.conf .
sed "73i[build]\nServer = file:///${basedir}/build-repo\nSigLevel = Never\n" -i ${repo}.conf

arch=$(uname -m)

# Cleanup package cache
arch-nspawn "${buildroot}/${repo}-${arch}/root" rm -f /var/cache/pacman/pkg/*

# Build package
_pushd ${packages_dir}/${package}
  arch-nspawn \
    -C "${basedir}/${repo}.conf" \
    -M "/usr/share/devtools/makepkg.conf.d/${arch}.conf" \
    "${buildroot}/${repo}-${arch}/root" \
    pacman -Syu --noconfirm
  setarch ${arch} sudo makechrootpkg -r "${buildroot}/${repo}-${arch}" -c -n
_popd
