#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

. ${SCRIPTPATH}/common

if [ "$#" -lt 1 ]; then
  echo "Usage: ${0} <repo>"
  echo "Example: ${0} extra"
  exit 1
fi

basedir=${PWD}
repo=$1
arch=$2

echo "Basedir is ${basedir}"

# Add temporary repository to pacman.conf
cp /usr/share/devtools/pacman.conf.d/${repo}.conf .
sed "73i[build]\nServer = file:///${basedir}/build-repo\nSigLevel = Never\n" -i ${repo}.conf

# Create temporary repository
mkdir -p build-repo
repo-add -n build-repo/build.db.tar > /dev/null 2>&1

# Pass i686 as argument if you want to build i686 packages on a x86_64 system
[[ -z ${arch} ]] && arch=$(uname -m)

# Cleanup package cache
arch-nspawn "${buildroot}/${repo}-${arch}/root" rm -f /var/cache/pacman/pkg/*

# Build packages
touch built-packages
for i in ${depPkgName}; do
  if grep -q -x $i built-packages > /dev/null ; then
    continue
  fi
  _pushd build/${i}
    arch-nspawn \
      -C "${basedir}/${repo}.conf" \
      -M "/usr/share/devtools/makepkg.conf.d/${arch}.conf" \
      "${buildroot}/${repo}-${arch}/root" \
      pacman -Syuu --noconfirm
    if setarch ${arch} sudo makechrootpkg -r "${buildroot}/${repo}-${arch}" -c -n ; then
      echo $i >> ${basedir}/built-packages
    else
      exit 1
    fi
    cp $(makepkg --packagelist) ${basedir}/build-repo
    repo-add -n ${basedir}/build-repo/build.db.tar ${basedir}/build-repo/*.pkg.tar.zst > /dev/null 2>&1
  _popd
done

for i in ${optPkgName}; do
  if grep -q -x $i built-packages ; then
    continue
  fi
  _pushd build/${i}
    arch-nspawn \
      -C "${basedir}/${repo}.conf" \
      -M "/usr/share/devtools/makepkg.conf.d/${arch}.conf" \
      "${buildroot}/${repo}-${arch}/root" \
      pacman -Syuu --noconfirm
    if setarch ${arch} sudo makechrootpkg -r "${buildroot}/${repo}-${arch}" -c -n ; then
      echo $i >> ${basedir}/built-packages
    else
      echo $i >> ${basedir}/broken-packages
    fi
  _popd
done

if [ -s broken-packages ]; then
  echo "Broken packages:"
  cat broken-packages
else
  echo "All packages built successfully!"
fi
