#!/bin/bash

echo "Starting to build packages";

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

. ${SCRIPTPATH}/common

basedir=${PWD}

echo "Basedir is ${basedir}"
echo "Buildroot is ${buildroot}"

echo Add temporary repository to pacman.conf
cp /usr/share/devtools/pacman.conf.d/${repo}.conf .
sed "73i[build]\nServer = file:///${basedir}/build-repo\nSigLevel = Never\n" -i ${repo}.conf

echo Create temporary repository
mkdir -p build-repo
repo-add -n build-repo/build.db.tar > /dev/null 2>&1

echo Cleanup package cache
arch-nspawn "${buildroot}/${repo}-${arch}/root" rm -fr /var/cache/pacman/pkg/*

echo Build packages
touch built-packages
for i in ${depPkgName}; do
  if grep -q -x $i built-packages > /dev/null ; then
    continue
  fi
  echo "Trying to build ${packages_dir}/${i}"
  _pushd ${packages_dir}/${i}
    arch-nspawn \
      -C "${basedir}/${repo}.conf" \
      -M "/usr/share/devtools/makepkg.conf.d/${arch}.conf" \
      "${buildroot}/${repo}-${arch}/root" \
      pacman -Syuu --noconfirm
    if sudo makechrootpkg -r "${buildroot}/${repo}-${arch}" -c -n ; then
      echo $i >> ${basedir}/built-packages
    else
      exit 1
    fi
    cp $(makepkg --packagelist) ${basedir}/build-repo
    repo-add -n ${basedir}/build-repo/build.db.tar ${basedir}/build-repo/*.pkg.tar.zst > /dev/null 2>&1
  _popd
done

for i in ${optPkgName}; do
  if grep -q -x $i built-packages ; then
    continue
  fi
  _pushd ${packages_dir}/${i}
    arch-nspawn \
      -C "${basedir}/${repo}.conf" \
      -M "/usr/share/devtools/makepkg.conf.d/${arch}.conf" \
      "${buildroot}/${repo}-${arch}/root" \
      pacman -Syuu --noconfirm
    if sudo makechrootpkg -r "${buildroot}/${repo}-${arch}" -c -n ; then
      echo $i >> ${basedir}/built-packages
    else
      echo $i >> ${basedir}/broken-packages
    fi
  _popd
done

cd ${basedir}
if [ -s broken-packages ]; then
  echo "Broken packages:"
  cat broken-packages
else
  echo "All packages built successfully!"
fi
