#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

. ${SCRIPTPATH}/common

if [ "$#" -lt 1 ]; then
  echo "Usage: ${0} <branch>"
  echo "Example: ${0} main"
  exit 1
fi

mkdir -p ${__PKG_REPO_ROOT_PATH__}
cd ${__PKG_REPO_ROOT_PATH__}

for i in ${depPkgName} ${optPkgName}; do
  if [ ! -d $i ]; then
    if ${__REMOTE_BUILD__}; then
      echo "Remote"
      pkgctl repo clone --protocol https $i 
    else
      echo "Local"
      pkgctl repo clone $i
    fi
  fi
  _pushd $i
    git checkout $1
    git pull origin $1
  _popd
done
