#!/bin/bash

if [ "$#" -lt 1 ]; then
  echo "Usage: ${0} <branch>"
  echo "Example: ${0} main"
  exit 1
fi

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

. ${SCRIPTPATH}/common

mkdir -p ${packages_dir}
cd ${packages_dir}

if $remote_build; then
  echo "REMOTE BUILD"
else
  echo "LOCAL BUILD"
fi
