#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

. ${SCRIPTPATH}/common

if [ "$#" -lt 2 ]; then
  echo "Usage: ${0} <branch> <commit-message>"
  echo "Example: ${0} main \"Update to new version\""
  exit 1
fi

cd ${__PKG_REPO_ROOT_PATH__}

for i in ${depPkgName} ${optPkgName}; do
  _pushd $i
    git commit -am "$2"
    git push origin $1
  _popd
done
