#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

. ${SCRIPTPATH}/common

cd ${packages_dir}

for i in ${depPkgName} ${optPkgName}; do
  _pushd $i
    git commit -am "Update to ${version}"
    git push origin $1
  _popd
done
