#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

. ${SCRIPTPATH}/common

if [[ ${suite} == 'kf6' ]]; then
    rsync -e ssh -rchL --progress --partial ftparchlinux@tinami.kde.org:${release}/frameworks/${version%.*}/ ${SRCDEST}/
elif [[ ${suite} == 'plasma' ]]; then
    rsync -e ssh -rchL --progress --partial ftparchlinux@tinami.kde.org:${release}/${suite}/${version}/ ${SRCDEST}/
elif [[ ${suite} == 'gear' ]]; then
    rsync -e ssh -rchL --progress --partial ftparchlinux@tinami.kde.org:${release}/release-service/${version}/src/ ${SRCDEST}/
fi
