#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

. ${SCRIPTPATH}/common

cd ${packages_dir}

for i in ${depPkgName} ${optPkgName}; do
  if [ -d $i ]; then
  pushd $i
    git diff
  popd
done
