#!/bin/bash

if [ "$#" -lt 2 ]; then
  echo "Usage: ${0} <origin> <dest>"
  echo "Example: ${0} kde-build main"
  exit 1
fi

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

. ${SCRIPTPATH}/common

mkdir -p ${packages_dir}
cd ${packages_dir}

for i in ${depPkgName} ${optPkgName}; do
  _pushd $i
    git checkout $1
    git checkout $2
    git pull
    git restore --source $1 .
  _popd
done
