#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

. ${SCRIPTPATH}/common

cd ${packages_dir}

for i in $(cat ${scriptroot}/package-list/${suite}/rebuild.list); do
  _pushd ${i}
    pkgctl release "$@" || exit 1
  _popd
done
