#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

. ${SCRIPTPATH}/common

cd ${__PKG_REPO_ROOT_PATH__}

for pkg in ${depPkgName} ${optPkgName}; do
  _pushd ${pkg}
  checkpkg
  _popd
done

