#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

. ${SCRIPTPATH}/common

cd ${packages_dir}

for pkg in ${depPkgName} ${optPkgName}; do
    _pushd ${pkg}
    for _pkgfile in $(makepkg --packagelist); do
        namcap ${_pkgfile} | tee namcap.log
    done
    _popd
done

cat namcap.log
