#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

. ${SCRIPTPATH}/common

cd ${packages_dir}

for pkg in ${depPkgName} ${optPkgName}; do
  _pushd ${pkg}
  checkpkg
  _popd
done

