#!/bin/bash

if [ "$#" -lt 1 ]; then
  echo "Usage: ${0} <suite> <stable|unstable> <version> <repo>"
  echo "Example: ${0} kf6 stable 6.0.0 extra-testing"
  exit 1
fi

rm -fr build-repo
rm -f *.conf
rm -f broken-packages
rm -f broken-rebuilds
rm -f built-packages
rm -f namcap.log
rm -f config
mkdir build-repo
touch build-repo/build.db{,.tar}

echo "suite=$1" >> config
[[ -n $2 ]] && echo "release=$2" >> config
[[ -n $3 ]] && echo "version=$3" >> config
[[ -n $4 ]] && echo "repo=$4" >> config
