#!/bin/bash

. common

if [ "$#" -lt 2 ]; then
  echo "Usage: ${0} <stable|unstable> <version>"
  echo "Example: ${0} stable 6.0.0"
  exit 1
fi

for i in ${depPkgName} ${optPkgName}; do

    _pushd build/${i}
    sed -r "s|https://download.kde.org/.*stable/|https://download.kde.org/$1/|g" -i PKGBUILD
    sed -r "s|pkgver=.*|pkgver=$2|g" -i PKGBUILD
    sed -r 's|pkgrel=.*|pkgrel=1|g' -i PKGBUILD
    updpkgsums
    _popd
done
