#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

. ${SCRIPTPATH}/common

for i in ${depPkgName} ${optPkgName}; do
    _pushd ${packages_dir}/${i}
    if [[ ${suite} == 'qt5' ]]; then
        commit=`git ls-remote https://invent.kde.org/qt/qt/${i/5-/}.git kde/5.15 | cut -f1`
        sed -r "s|_commit=.*|_commit=${commit}|g" -i PKGBUILD
        sed -r "s|_basever=.*|_basever=${version}|g" -i PKGBUILD
    elif [[ ${suite} == 'qt6' ]]; then
        sed -r "s|pkgver=.*|pkgver=${version}|g" -i PKGBUILD
    else
        sed -r "s|pkgver=.*|pkgver=${version}|g" -i PKGBUILD
    fi
    sed -r "s|https://download.kde.org/.*stable/|https://download.kde.org/${release}/|g" -i PKGBUILD
    if [[ ${i} == 'qt5-webengine' || ${i} == 'qt5-script' ]]; then
        setconf PKGBUILD pkgrel+=1
    else
        sed -r 's|pkgrel=.*|pkgrel=1|g' -i PKGBUILD
    fi
    updpkgsums
    _popd
done
